# Generated by Django 4.0.5 on 2022-08-04 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_headingandsubheading_productpaymentmethod_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='heading',
        ),
    ]
