# Generated by Django 4.0.5 on 2022-08-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productsolutionimage_productsolutioncontent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoutcomecontent',
            name='content',
            field=models.TextField(verbose_name='productContent'),
        ),
        migrations.AlterField(
            model_name='productoutcomecontent',
            name='title',
            field=models.CharField(max_length=250, verbose_name='productTitle'),
        ),
        migrations.AlterField(
            model_name='productsolutioncontent',
            name='content',
            field=models.TextField(verbose_name='productContent'),
        ),
        migrations.AlterField(
            model_name='productsolutioncontent',
            name='title',
            field=models.CharField(max_length=250, verbose_name='productTitle'),
        ),
    ]
