# Generated by Django 4.0.5 on 2022-07-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('image', models.ImageField(upload_to='about', verbose_name='image')),
                ('slug', models.SlugField(blank=True, max_length=100, verbose_name='aboutSlug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creationDate')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updatedDate')),
            ],
            options={
                'verbose_name_plural': 'About',
            },
        ),
        migrations.CreateModel(
            name='ContactAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.CharField(max_length=250, unique=True, verbose_name='officeName')),
                ('location', models.TextField(verbose_name='officeLocation')),
                ('phone', models.CharField(blank=True, default='', help_text='use , seperator for officeNumber', max_length=500, null=True, verbose_name='officeNumbers')),
                ('email', models.CharField(blank=True, default='', help_text='use , seperator for officeEmails', max_length=500, null=True, verbose_name='officeEmails')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creationDate')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updatedDate')),
            ],
            options={
                'verbose_name_plural': 'Contact Address',
            },
        ),
    ]
