# Generated by Django 4.0.5 on 2022-08-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BecomeOurPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250, verbose_name='firstName')),
                ('last_name', models.CharField(max_length=250, verbose_name='lastName')),
                ('email', models.EmailField(max_length=250, verbose_name='email')),
                ('contact', models.CharField(max_length=250, verbose_name='contactNumber')),
                ('address', models.TextField(max_length=250, verbose_name='address')),
                ('state', models.CharField(max_length=250, verbose_name='state')),
                ('city', models.CharField(max_length=250, verbose_name='city')),
                ('source', models.CharField(max_length=250, verbose_name='How did you hear from us ')),
                ('source_optional', models.TextField(help_text='Optional', max_length=250, verbose_name='sourceOptional')),
                ('notes', models.TextField(help_text='Optional', max_length=250, verbose_name='notesOptional')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creationDate')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updatedDate')),
            ],
        ),
    ]
