# Generated by Django 4.0.5 on 2022-08-02 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0002_becomeourpartner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='becomeourpartner',
            options={'verbose_name_plural': 'Become Our Partner'},
        ),
    ]
