# Generated by Django 4.0.5 on 2022-08-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_blockchain_blockchain_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurUnparalleledService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='UnparalleledServiceTitle')),
                ('content', models.TextField(verbose_name='UnparalleledServiceContent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creationDate')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updatedDate')),
            ],
        ),
    ]
