# Generated by Django 4.0.5 on 2022-08-03 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0003_ourunparalleledservice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ourunparalleledservice',
            options={'verbose_name_plural': 'Our Unparalleled Service'},
        ),
    ]
