# Generated by Django 4.0.5 on 2022-08-03 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0004_alter_ourunparalleledservice_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourunparalleledservice',
            name='blockchain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blockchain.blockchain'),
        ),
        migrations.CreateModel(
            name='DummySection3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='UnparalleledServiceTitle')),
                ('content', models.TextField(verbose_name='UnparalleledServiceContent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creationDate')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updatedDate')),
                ('blockchain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blockchain.blockchain')),
            ],
            options={
                'verbose_name_plural': 'Dummy Section 3',
            },
        ),
        migrations.CreateModel(
            name='DummySection2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='UnparalleledServiceTitle')),
                ('content', models.TextField(verbose_name='UnparalleledServiceContent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creationDate')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updatedDate')),
                ('blockchain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blockchain.blockchain')),
            ],
            options={
                'verbose_name_plural': 'Dummy Section 2',
            },
        ),
    ]
