# Generated by Django 4.0.5 on 2022-08-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0005_ourunparalleledservice_blockchain_dummysection3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummysection2',
            name='content',
            field=models.TextField(verbose_name='dummySectionContent'),
        ),
        migrations.AlterField(
            model_name='dummysection2',
            name='title',
            field=models.CharField(max_length=500, verbose_name='dummySectionTitle'),
        ),
        migrations.AlterField(
            model_name='dummysection3',
            name='content',
            field=models.TextField(verbose_name='dummySectionContent'),
        ),
        migrations.AlterField(
            model_name='dummysection3',
            name='title',
            field=models.CharField(max_length=500, verbose_name='dummySectionTitle'),
        ),
    ]
