# Generated by Django 4.0.5 on 2022-08-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0006_alter_dummysection2_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadingAndSubheading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subheading', models.CharField(max_length=500, verbose_name='homepageSubheading')),
                ('heading', models.TextField(blank=True, null=True, verbose_name='homepageHeading')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creationDate')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updatedDate')),
            ],
            options={
                'verbose_name_plural': 'Heading & Subheading',
            },
        ),
        migrations.RemoveField(
            model_name='blockchain',
            name='blockchain_content',
        ),
        migrations.DeleteModel(
            name='BlockchainService',
        ),
    ]
