# Generated by Django 4.0.5 on 2022-08-05 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0007_headingandsubheading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummysection2',
            name='heading',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blockchain.headingandsubheading'),
        ),
        migrations.AddField(
            model_name='dummysection3',
            name='heading',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blockchain.headingandsubheading'),
        ),
        migrations.AddField(
            model_name='ourunparalleledservice',
            name='heading',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blockchain.headingandsubheading'),
        ),
    ]
