# Generated by Django 4.0.5 on 2022-08-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0009_remove_dummysection2_heading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummysection2',
            name='subheading',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='subHeading'),
        ),
        migrations.AddField(
            model_name='dummysection3',
            name='subheading',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='subHeading'),
        ),
        migrations.AddField(
            model_name='ourunparalleledservice',
            name='subheading',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='subHeading'),
        ),
    ]
