# Generated by Django 4.0.5 on 2022-08-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0010_dummysection2_subheading_dummysection3_subheading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummysection2',
            name='image',
            field=models.ImageField(null=True, upload_to='blockchain_section_1'),
        ),
        migrations.AddField(
            model_name='dummysection3',
            name='image',
            field=models.ImageField(null=True, upload_to='blockchain_section_1'),
        ),
        migrations.AddField(
            model_name='ourunparalleledservice',
            name='image',
            field=models.ImageField(null=True, upload_to='blockchain_section_1'),
        ),
    ]
