# Generated by Django 4.0.5 on 2022-08-06 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0011_dummysection2_image_dummysection3_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dummysection2',
            options={'verbose_name_plural': 'Blockchain Section 2'},
        ),
        migrations.AlterModelOptions(
            name='dummysection3',
            options={'verbose_name_plural': 'Blockchain Section 3'},
        ),
        migrations.AlterModelOptions(
            name='ourunparalleledservice',
            options={'verbose_name_plural': 'Blockchain Section 1'},
        ),
    ]
