# Generated by Django 4.0.5 on 2022-08-10 08:54

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0013_headingandsubheading_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummysection2',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='dummySectionContent'),
        ),
        migrations.AlterField(
            model_name='dummysection2',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='dummySectionTitle'),
        ),
        migrations.AlterField(
            model_name='dummysection3',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='dummySectionContent'),
        ),
        migrations.AlterField(
            model_name='dummysection3',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='dummySectionTitle'),
        ),
        migrations.AlterField(
            model_name='ourunparalleledservice',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='dummySectionContent'),
        ),
        migrations.AlterField(
            model_name='ourunparalleledservice',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='UnparalleledServiceTitle'),
        ),
    ]
