# Generated by Django 4.0.5 on 2022-08-10 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0014_alter_dummysection2_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headingandsubheading',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='headingandsubheading',
            name='subheading',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='homepageSubheading'),
        ),
        migrations.CreateModel(
            name='BlockchainService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockchain_service_name', models.CharField(max_length=250, verbose_name='blockchainServiceName')),
                ('blockchain_content', models.TextField(blank=True, default='', null=True, verbose_name='blockchainContent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creationDate')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updatedDate')),
                ('blockchain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockchain.blockchain')),
                ('heading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockchain.headingandsubheading')),
            ],
            options={
                'verbose_name_plural': 'Blockchain Service',
            },
        ),
    ]
