# Generated by Django 4.0.5 on 2022-08-02 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='NftDescription'),
        ),
        migrations.CreateModel(
            name='NFTUseCases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='useCasesTitle')),
                ('content', models.TextField(verbose_name='useCasesContent')),
                ('icon', models.ImageField(upload_to='nft_use_cases', verbose_name='useCasesIcon')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creationDate')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updatedDate')),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nft.nft')),
            ],
        ),
        migrations.CreateModel(
            name='NFTMarketplaceDevelopmentService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='serviceTitle')),
                ('content', models.TextField(verbose_name='serviceContent')),
                ('icon', models.ImageField(upload_to='nft_use_cases', verbose_name='serviceIcon')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creationDate')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updatedDate')),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nft.nft')),
            ],
        ),
    ]
