# Generated by Django 4.0.5 on 2022-07-30 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, verbose_name='NftSlug'),
        ),
    ]
