# Generated by Django 4.0.5 on 2022-08-02 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0002_nft_description_nftusecases_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nftmarketplacedevelopmentservice',
            options={'verbose_name_plural': 'NFT Marketplace Development Service'},
        ),
        migrations.AlterModelOptions(
            name='nftusecases',
            options={'verbose_name_plural': 'NFT Use Cases'},
        ),
    ]
