# Generated by Django 4.0.5 on 2022-08-08 06:56

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0003_alter_nftmarketplacedevelopmentservice_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadingAndSubheading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subheading', models.CharField(max_length=500, verbose_name='homepageSubheading')),
                ('heading', models.TextField(blank=True, null=True, verbose_name='homepageHeading')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creationDate')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updatedDate')),
            ],
            options={
                'verbose_name_plural': 'Heading & Subheading',
            },
        ),
        migrations.CreateModel(
            name='NFTSection2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=500, verbose_name='nftSection2Heading')),
                ('title', models.TextField(blank=True, null=True, verbose_name='nftSection2Title')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='nftSection2Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creationDate')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updatedDate')),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nft.nft')),
            ],
        ),
    ]
