# Generated by Django 4.0.5 on 2022-08-08 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0004_headingandsubheading_nftsection2'),
    ]

    operations = [
        migrations.AddField(
            model_name='nftmarketplacedevelopmentservice',
            name='heading',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nft.headingandsubheading'),
        ),
        migrations.AddField(
            model_name='nftusecases',
            name='heading',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nft.headingandsubheading'),
        ),
    ]
