# Generated by Django 4.0.5 on 2022-08-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0005_nftmarketplacedevelopmentservice_heading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='headingandsubheading',
            name='description',
            field=models.TextField(default='', verbose_name='description'),
        ),
    ]
