# Generated by Django 4.0.5 on 2022-08-01 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_developmentprocess'),
    ]

    operations = [
        migrations.RenameField(
            model_name='developmentprocess',
            old_name='process',
            new_name='title',
        ),
    ]
