# Generated by Django 4.0.5 on 2022-08-04 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_whatwedo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadingAndSubheading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subheading', models.CharField(max_length=500, verbose_name='homepageSubheading')),
                ('heading', models.TextField(verbose_name='homepageHeading')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creationDate')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updatedDate')),
            ],
            options={
                'verbose_name_plural': 'Heading & Subheading',
            },
        ),
        migrations.AddField(
            model_name='developmentprocess',
            name='heading_and_subheading',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.headingandsubheading'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='heading_and_subheading',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.headingandsubheading'),
        ),
        migrations.AddField(
            model_name='notableblockchainplatforms',
            name='heading_and_subheading',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.headingandsubheading'),
        ),
        migrations.AddField(
            model_name='ourmastery',
            name='heading_and_subheading',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.headingandsubheading'),
        ),
        migrations.AddField(
            model_name='whatwedo',
            name='heading_and_subheading',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.headingandsubheading'),
        ),
        migrations.AddField(
            model_name='whychooseus',
            name='heading_and_subheading',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.headingandsubheading'),
        ),
    ]
