# Generated by Django 4.0.5 on 2022-08-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_headingandsubheading_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herosection',
            name='heading_and_subheading',
        ),
        migrations.AlterField(
            model_name='headingandsubheading',
            name='heading',
            field=models.TextField(null=True, verbose_name='homepageHeading'),
        ),
        migrations.DeleteModel(
            name='NotableBlockchainPlatforms',
        ),
    ]
