# Generated by Django 4.0.5 on 2022-08-06 12:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_blogsection_startsomethingundeniably_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whychooseus',
            name='icon',
            field=models.FileField(upload_to='why_choose_us', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg'])], verbose_name='icon'),
        ),
    ]
