# Generated by Django 4.0.5 on 2022-08-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_alter_whychooseus_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonialsection',
            name='image',
            field=models.ImageField(null=True, upload_to='testimonials', verbose_name='clientImage'),
        ),
        migrations.AlterField(
            model_name='testimonialsection',
            name='content',
            field=models.TextField(verbose_name='testimonialsContent'),
        ),
        migrations.AlterField(
            model_name='testimonialsection',
            name='subheading',
            field=models.CharField(max_length=500, verbose_name='testimonialSubheading'),
        ),
    ]
