# Generated by Django 4.0.5 on 2022-08-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_herosection_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='official_link',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='official_link'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='slug',
            field=models.SlugField(max_length=200, null=True, verbose_name='slug'),
        ),
    ]
