# Generated by Django 4.0.5 on 2022-08-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_herosection_official_link_herosection_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='official_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='official_link'),
        ),
    ]
