# Generated by Django 4.0.5 on 2022-08-09 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0017_alter_herosection_official_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, verbose_name='slug'),
        ),
    ]
