# Generated by Django 4.0.5 on 2022-08-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0020_alter_blogsection_subheading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsection',
            name='subheading',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='blogSubheading'),
        ),
        migrations.AlterField(
            model_name='headingandsubheading',
            name='heading',
            field=models.TextField(blank=True, default='', null=True, verbose_name='homepageHeading'),
        ),
        migrations.AlterField(
            model_name='headingandsubheading',
            name='subheading',
            field=models.CharField(default='', max_length=500, verbose_name='homepageSubheading'),
        ),
        migrations.AlterField(
            model_name='startsomethingundeniably',
            name='subheading',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='subHeading'),
        ),
        migrations.AlterField(
            model_name='testimonialsection',
            name='subheading',
            field=models.CharField(default='', max_length=500, verbose_name='testimonialSubheading'),
        ),
        migrations.AlterField(
            model_name='whatwedo',
            name='heading',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='whatWeDoHeading'),
        ),
    ]
