# Generated by Django 4.0.5 on 2022-08-09 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_headingandsubheading_description'),
        ('homepage', '0021_alter_blogsection_subheading_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HeroSection',
            new_name='Banner',
        ),
    ]
