# Generated by Django 4.0.5 on 2022-08-09 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0022_rename_herosection_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name_plural': 'Banner'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name_plural': 'Our Partners'},
        ),
    ]
