# Generated by Django 4.0.5 on 2022-08-09 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0023_alter_banner_options_alter_partner_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StartSomethingUndeniably',
            new_name='BlockchainTechnology',
        ),
    ]
