# Generated by Django 4.0.5 on 2022-08-09 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0024_rename_startsomethingundeniably_blockchaintechnology'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OurMastery',
            new_name='ProfessionalBlockchainDevelopmentCompany',
        ),
        migrations.AlterModelOptions(
            name='professionalblockchaindevelopmentcompany',
            options={'verbose_name_plural': 'Professional Blockchain Development Company'},
        ),
    ]
