# Generated by Django 4.0.5 on 2022-08-09 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0025_rename_ourmastery_professionalblockchaindevelopmentcompany_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockchaintechnology',
            options={'verbose_name_plural': 'Blockchain Technology'},
        ),
        migrations.AlterModelOptions(
            name='blogsection',
            options={'verbose_name_plural': 'Our Blogs'},
        ),
        migrations.AlterModelOptions(
            name='contactinformation',
            options={'verbose_name_plural': 'Contact Information'},
        ),
        migrations.AlterModelOptions(
            name='getintouch',
            options={'verbose_name_plural': 'Get In Touch'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['id'], 'verbose_name_plural': 'Testimonial'},
        ),
        migrations.AlterModelOptions(
            name='testimonialsection',
            options={'verbose_name_plural': 'Testimonial Section'},
        ),
    ]
