# Generated by Django 4.0.5 on 2022-08-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_company', '0004_privacypolicy_termsandcondition'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacypolicy',
            name='title',
            field=models.CharField(default='Privacy Policy', max_length=100, verbose_name='privacyPolicyTitle'),
        ),
        migrations.AddField(
            model_name='termsandcondition',
            name='title',
            field=models.CharField(default='Term & Condition', max_length=100, verbose_name='termAndConditionTitle'),
        ),
    ]
