# Generated by Django 4.0.5 on 2022-08-05 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about_company', '0006_aboutcompany_aboutcompanysection1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCompanySection3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about_section_3')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(verbose_name='aboutCompany')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creationDate')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updatedDate')),
                ('heading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about_company.headingandsubheading')),
            ],
            options={
                'verbose_name_plural': 'About Company Section 3',
            },
        ),
    ]
