# Generated by Django 4.0.5 on 2022-08-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_company', '0008_alter_aboutcompany_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='headingandsubheading',
            name='description',
            field=models.TextField(default='', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='aboutcompany',
            name='heading',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
