# Generated by Django 4.0.5 on 2022-08-10 09:53

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about_company', '0011_alter_headingandsubheading_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchainforbusiness',
            name='image',
            field=models.ImageField(upload_to='blockchain_for_business'),
        ),
        migrations.CreateModel(
            name='VisionAndMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vision_and_mission')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='mission&vision')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creationDate')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updatedDate')),
                ('heading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about_company.headingandsubheading')),
            ],
            options={
                'verbose_name_plural': 'Vision And Mission',
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Partners')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creationDate')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updatedDate')),
                ('heading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about_company.headingandsubheading')),
            ],
            options={
                'verbose_name_plural': 'Partner',
            },
        ),
    ]
