# Generated by Django 4.0.5 on 2022-08-10 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_company', '0013_faqs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqs',
            name='title',
        ),
    ]
