# Generated by Django 4.0.5 on 2022-08-10 11:59

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about_company', '0014_remove_faqs_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='build_connection')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='BuildConnectionContent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creationDate')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updatedDate')),
                ('heading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about_company.headingandsubheading')),
            ],
        ),
    ]
