# Generated by Django 4.0.5 on 2022-08-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_company', '0016_rename_description_buildconnection_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildconnection',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='BuildConnectionContent'),
        ),
    ]
