# Generated by Django 4.0.5 on 2022-07-29 13:34

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='careers',
            name='responsibilities',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='careerResponsibilities'),
        ),
        migrations.AddField(
            model_name='careers',
            name='skills',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='careerSkills'),
        ),
        migrations.AlterField(
            model_name='careers',
            name='experience',
            field=models.CharField(help_text='for example : 6 Months - 1 Year', max_length=250, null=True, verbose_name='experience'),
        ),
    ]
