# Generated by Django 4.0.5 on 2022-08-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_careers_join_duration_careers_opening_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='careers',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True, verbose_name='careerSlug'),
        ),
    ]
