# Generated by Django 4.0.5 on 2022-08-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_careers_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyForJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='candidateName')),
                ('email', models.EmailField(max_length=254, verbose_name='candidateEmail')),
                ('contact', models.CharField(max_length=100, verbose_name='candidateContactNumber')),
                ('state', models.CharField(max_length=200, verbose_name='state')),
                ('city', models.CharField(max_length=200, verbose_name='city')),
                ('address', models.TextField(verbose_name='candidateAddress')),
                ('skill_set', models.TextField(verbose_name='skillSet')),
                ('resume', models.FileField(upload_to='resume', verbose_name='candidateResume')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creationDate')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updatedDate')),
            ],
        ),
    ]
