# Generated by Django 4.0.5 on 2022-08-03 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_applyforjob'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applyforjob',
            options={'verbose_name_plural': 'Apply For Job'},
        ),
    ]
