# Generated by Django 4.0.5 on 2022-08-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='modernsolutionforvariousplatform',
            name='subheading',
            field=models.CharField(default='', max_length=500, verbose_name='modernSolutionSubHeading'),
        ),
    ]
