# Generated by Django 4.0.5 on 2022-08-08 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_headingandsubheading'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesection2',
            name='heading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.headingandsubheading'),
        ),
    ]
