# Generated by Django 4.0.5 on 2022-08-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, verbose_name='resourceName')),
                ('image', models.ImageField(upload_to='resources', verbose_name='resourceImage')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, verbose_name='resourceSlug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creationDate')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updatedDate')),
            ],
            options={
                'verbose_name_plural': 'Resource',
            },
        ),
    ]
